---
title: ""
date: today
lang: ja
format: 
  html: 
    grid: 
      body-width: 1024px
    highlight-style: ally
    number-sections: false
    embed-resources: true
knitr: 
  opts_chunk: 
    dev: ragg_png
    fig-align: center
    dpi: 144
    message: false
---

## Qualtを使ったHPの作り方
<p>

当方，24歳にして初めてHPを作りました。<br>
修士の2年間でHPを作らないとな～と放置していたのですが，指導教員に「そろそろ...」と背中を押してもらってやっと作りました(笑)<br>
HPをQualtで作成したのは，「**サーバーを契約しなくてもGithubなら無料でできるよ**」とkrdさんが優しく教えてくださったからです。他にも，**Markdownが分かる人にとって敷居が低いこと**と**研究における分析の透明性の向上**が利点です。<br>
それでは，QualtをダウンロードするところからGithubで公開するまでを紹介します。<br>

(目次は右にあります。)
</p>

## 事前準備
### Quartoをダウンロードする



### RStudioの最新版をインストールする



### RStudioでプロジェクトを作る




## HPの中身を作る
### index.qmdはHPの内容
index.qmdファイルは，YAMLヘッダー，テキスト，チャンクで構成され，それぞれ，ページの構成を作るところ，本文を書くところ，コードを書くところです。

（図）

#### YAMLヘッダーを設定
YAMLは～～の略です。



#### テキストの編集


#### コードの編集
Rコードを書くための領域「```{r}   ```」をするショートカットコマンドは「cntr + alt + i」です。


### _quarto.ymlはHPのテーマや構成，出力形式などの指定
#### project：はプロジェクトの種類(website/article等)や挙動を指定


#### website：タイトルやナビバーなど，見た目や構造を指定


#### format：出力形式(HTML/pdfなど)やテーマなどを指定


### styles.cssは文章をオシャレにするところ



## HPをGithubに登録する
### Githubの設定


### RStudioの「Terminal」でHPを公開する


### HPを更新する
1.  新しく.qmdファイルを作成したときは，_quarto.ymlのnavber: に追加する
2.  Terminalを開く
3.  「quarto render --output-dir docs」と入力
4.  「git add .」を入力
5.  「git commit -m "Update Quarto files"」と入力
6.  「git push origin main」と入力
数十秒～数分待つと反映される。

自分のURLはGithub > Setting > Pagesで一番上に表示されているはずです。



