---
title: ""
email: marina.miki25@gmail.com
date: today
lang: ja

format: 
  html: 
    grid: 
      body-width: 1024px
    highlight-style: ally
    number-sections: false
    embed-resources: true

knitr: 
  opts_chunk: 
    dev: ragg_png
    fig-align: center
    dpi: 144
    message: false
---

## 業績 Works

### 論文

<strong>\[紀要論文：査読あり\]</strong>

1.  三木 毬菜・清水裕士 (2024). 将来の他者との資源分配における時間選好と社会選好 ―ベイズ統計モデリングによるモデル比較から―. KG社会学批評, 13: 69-79.

<strong>\[報告書：査読なし\]</strong>

1.  三木 毬菜・小原 直将・徳永 健斗・雪定 弦生・水野 景子 (2024). フューチャー・デザインの社会学・社会心理学への応用可能性を検討する 研究班活動報告. KG社会学批評, 13: 81-84 .

### 学会発表

1.  三木毬菜・清水裕士(2024). 持続可能な選択率の変動―現世代と将来世代への行動比較とモデルからの検討―. 日本行動計量学会第52回大会 2024年9月10日- 9月13日

2.  三木毬菜・清水裕士 (2024). 後続世代数と世代を超えた協力行動の関係：探索的調査報告. 日本社会心理学会第65回大会. 日本大学. 8月31-9月1日 (口頭発表)

3.  三木毬菜・清水裕士 (2024). 世代間/内ジレンマにおける協力行動の検討：数理モデルと実験からの検討. 第27回実験社会科学カンファレンス 2024年7月20日 - 7月21日

4.  三木毬菜・清水裕士 (2024). 世代間ジレンマにおける意思決定―社会選好を考慮した数理モデルによる検討―. ワークショップ：ヒトの協力行動の理解ー間接互恵性とその周辺ー. 総合研究大学院大学. 1月20日- 1月21日 (ポスター発表)

5.  三木毬菜・清水裕士 (2023). 世代間持続可能性ジレンマゲームにおける意思決定メカニズムの検討 社会選好を考慮したモデルの提案 第26回実験社会科学カンファレンス. 早稲田大学. 11月25日- 11月26日 (口頭発表)

6.  三木毬菜・水野景子・清水裕士 (2023). 個人は他者の協力に対する期待をどのように見積もるのか 日本社会心理学会第64回大会. 上智大学. 9月7日- 9月8日 (ポスター発表)

7.  三木毬菜・水野景子・清水裕士 (2023). 他者の協力期待がどのように見積もられるのか(2)―モデルによる検討― 日本行動計量学会第51回大会. 青山学院大学. 8月28日~ 8月31日 (口頭発表)

### 受賞・研究費など

<strong>\[研究助成・奨学金\]</strong>

1.  三木 毬菜 (2024). 想起する他者の違いによる持続可能な選択の採択率の変動―数理モデルと実験からの検討― 行動計量 学会 岡太彬訓研究助成 採択 2024 年 2 月

2.  三木 毬菜 (2023). 公益財団法人 近藤記念財団奨学金 採択 2023 年 12 月

<strong>\[受賞歴\]</strong>

1.  三木 毬菜 (2023). 遠い将来のことを考えると持続可能な選択を取れなくなる？：世代間協力割引仮説. 研究者奨励賞受賞. 社会心理学会 2023 年 12 月

2.  三木 毬菜 (2023).認知的感情制御方略が脱中心化を媒介して精神的健康に影響する. 高知工科大学ベストプロジェクト研究賞受賞. 2023 年 3 月

3.  三木 毬菜 (2022). 高知工科大学 学業成績優秀賞受賞. 2022 年 11 月

4.  三木 毬菜 (2021). 高知工科大学 廣井勇賞受賞. 2021 年 11 月
